In [1]:
!pip3 install torch torchvision

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import numpy as np

In [2]:
class SingleRNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super(SingleRNN, self).__init__()

        self.Wx = torch.randn(n_inputs, n_neurons) # 4 X 1
        self.Wy = torch.randn(n_neurons, n_neurons) # 1 X 1
        
        self.b = torch.zeros(1, n_neurons) # 1 X 4
    
    def forward(self, X0, X1):
        self.Y0 = torch.tanh(torch.mm(X0, self.Wx) + self.b) # 4 X 1
        
        self.Y1 = torch.tanh(torch.mm(self.Y0, self.Wy) +
                            torch.mm(X1, self.Wx) + self.b) # 4 X 1
        
        return self.Y0, self.Y1

In [3]:
N_INPUT = 4
N_NEURONS = 1

X0_batch = torch.tensor([[0,1,2,0], [3,4,5,0], 
                         [6,7,8,0], [9,0,1,0]],
                        dtype = torch.float) #t=0 => 4 X 4

X1_batch = torch.tensor([[9,8,7,0], [0,0,0,0], 
                         [6,5,4,0], [3,2,1,0]],
                        dtype = torch.float) #t=1 => 4 X 4

model = SingleRNN(N_INPUT, N_NEURONS)

Y0_val, Y1_val = model(X0_batch, X1_batch)

In [4]:
Y0_val

tensor([[ 0.9612],
        [ 0.9998],
        [ 1.0000],
        [-0.9939]])

In [5]:
Y1_val

tensor([[ 0.9999],
        [-0.4268],
        [ 0.9907],
        [ 0.7786]])

In [6]:
#RNN Layer having more than 1 neuron

class SimpleRNN(nn.Module):

  def __init__(self,n_inputs,n_neurons):
    super(SimpleRNN,self).__init__()

    self.w_X=torch.randn(n_inputs,n_neurons)
    self.w_Y=torch.randn(n_neurons,n_neurons)
    self.bias=torch.zeros(1,n_neurons)

  def forward(self,X0,X1):

    self.Y0=torch.tanh(torch.mm(X0,self.w_X)+self.bias)
    self.Y1=torch.tanh(torch.mm(self.Y0,self.w_Y)+torch.mm(X1,self.w_X)+self.bias)

    return self.Y0,self.Y1

In [7]:
n_inputs=4
n_neurons=5

X0_batch = torch.tensor([[0,1,2,2], [3,4,5,5], 
                         [6,7,8,8], [9,0,1,1]],
                        dtype = torch.float)

X1_batch = torch.tensor([[9,8,7,7], [0,0,0,0], 
                         [6,5,4,4], [3,2,1,1]], 
                        dtype = torch.float)


In [9]:
model=SimpleRNN(n_inputs,n_neurons)

In [11]:
out_Y0,out_Y1=model(X0_batch,X1_batch)

In [12]:
out_Y0

tensor([[ 0.9987, -0.8558,  0.9288, -0.9955,  0.9030],
        [ 0.9447, -0.9996,  0.9999, -1.0000, -0.9978],
        [-0.1007, -1.0000,  1.0000, -1.0000, -1.0000],
        [-1.0000, -0.9553,  0.7332,  1.0000, -1.0000]])

In [13]:
out_Y1

tensor([[-1.0000, -0.9998,  1.0000, -1.0000, -1.0000],
        [ 0.4457,  0.9913, -1.0000,  0.6868, -0.0106],
        [-1.0000, -0.9984,  0.3518, -0.9994, -1.0000],
        [-1.0000, -1.0000,  0.3193, -0.7458, -1.0000]])